project:
  type: website
  output-dir: docs

website:
  title: "Working notes"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Rhys-McAlister
      - icon: twitter
        href: https://twitter.com/mcalister_rhys
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

