---
title: "Tidymodels in R"
editor: visual
author: Rhys McAlister
subtitle: A record of my progress learning the Tidymodels library.
date: 2022/10/22
toc: true
toc-depth: 2
title-block-banner: true
bibliography: references.bib
---

[Tidymodels official tutorial set](https://www.tidymodels.org/start/models/).

# Building a model

```{r}
#| warning: false
#| echo: false
library(tidymodels)  # for the parsnip package, along with the rest of tidymodels
library(tidyverse)
# Helper packages
library(readr)       # for importing data
library(broom.mixed) # for converting bayesian models to tidy tibbles
library(dotwhisker)  # for visualizing regression results
```

```{r}
#| warning: false
#| echo: false
urchins <-
  read_csv("https://tidymodels.org/start/models/urchins.csv") %>% 
  setNames(c("food_regime", "initial_volume", "width")) %>% 
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

```

```{r}
knitr::kable(head(urchins))
```

```{r}
ggplot(urchins,
       aes(x = initial_volume, 
           y = width, 
           group = food_regime, 
           col = food_regime)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  scale_color_viridis_d(option = "plasma", end = .7)

```
