{
  "hash": "1a641b08e3201d1637f6d05657009418",
  "result": {
    "markdown": "---\ntitle: \"Simple Linear Regression\"\nauthor: \"Rhys McAlister\"\ndate: \"2022-09-19\"\ncategories: [news, code, analysis]\nimage: \"image.jpg\"\nbibliography: references.bib\n---\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nsns.set(style='darkgrid')\nfrom sklearn.linear_model import LinearRegression\n```\n:::\n\n\n*Note: Information in this article is derived from the book 'Practical Statistics for Data Scientists'.*\n\nSimple linear regression can be used to derive a model of the relationship present between the magnitude of one variable and that of another.\n\nThe dataset below contains records of the numbers of years a given worker has been exposed to cotton dust ('Exposure') versus a metric used to describe ones lung capacity (peak expiratory flow rate, 'PEFR').\n\nFrom this graph it is hard to judge the relationship between these two variables by eye, especially if one was intending to make a prediction from the association of the two variables.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nlung = pd.read_csv('LungDisease.csv')\nsns.scatterplot(data=lung, x='Exposure',y='PEFR')\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n<AxesSubplot:xlabel='Exposure', ylabel='PEFR'>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-3-output-2.png){width=597 height=428}\n:::\n:::\n\n\nIf one did intend to make a prediction regarding the lung capacity of a worker after some defined period of exposure, a linear regression model would be appropriate.\n\nSimple linear regression provides an estimate of how much the response variable, Y will change when the predictor variable, X changes by a specified amount. This regression relationship is given by:\n\nY=b0+b1XY = b_0 + b_1 XY=b0​+b1​X\n\nWhere;\n\nb0b_0b0​: The intercept\nb1b_1b1​: Slope\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\npredictors = ['Exposure']\noutcome = 'PEFR'\nlm = LinearRegression()\nlm.fit(lung[predictors], lung[outcome])\nprint(f'Intercept: {lm.intercept_:.3f}')\nprint(f'Coefficient Exposure: {lm.coef_[0]:.3f}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIntercept: 424.583\nCoefficient Exposure: -4.185\n```\n:::\n:::\n\n\nThe intercept can be interpreted in this context as the predicted lung capacity or 'PEFR' of a worker who has had zero years of exposure to cotton dust. The regression coefficient or slope can be interpreted as the change in lung capacity for each year of exposure to cotton dust.\n\nSo it can be seen that a worker who has yet to be exposed to cotton dust is predicted to have a PEFR value of 424.583 and for every year of exposure to cotton dust that value is expected to decrease by 4.185.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nsns.regplot(data=lung,x='Exposure', y='PEFR')\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n<AxesSubplot:xlabel='Exposure', ylabel='PEFR'>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-5-output-2.png){width=597 height=428}\n:::\n:::\n\n\nThe regression line is the plot above indicates the 'fitted values' or the predictions derived from the linear regression model. It can be seen that generally the data doesn't fall exactly on the regression line and this deviation can be quantified as the 'residuals'.\n\nThis concept of residual values underlines the manner in which our linear model is fit to the data set. The regression line itself is defined as the estimate that minimises the sum of the squared residual values, this is known as the residual sum of squares (RSS). This method of minimising the RSS is also referred to as least squares regression or ordinary least squares regression.\n\nRegression analysis is primarily used to bring light to a supposed linear relationship between a set of predictor variables and a response variable. Our primary goal is to understand this association and explain it using the data one has. In the case of this dataset is can be seen that exposure to cotton dust has a deleterious effect on the lung capacity of workers and predictions of this effect can be quantified using the derived regression coefficient (b^\\hat{b}b\\^).\n\nReferences:\n\nBruce, Peter, Andrew Bruce, and Peter Gedeck. Practical statistics for data scientists: 50+ essential concepts using R and Python. O'Reilly Media, 2020.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}